# Classes
module OpenAPIParser
  class Config
    @config: untyped
    alias request_body_options request_validator_options
    alias path_params_options request_validator_options

    def initialize: (untyped config) -> untyped
    def datetime_coerce_class: -> (singleton(Object) | nil)
    def coerce_value: -> bool
    def expand_reference: -> bool
    def strict_response_validation: -> bool
    def validate_header: -> bool
    def request_validator_options: -> OpenAPIParser::SchemaValidator::Options
    def response_validate_options: -> OpenAPIParser::SchemaValidator::ResponseValidateOptions
  end
end
