require_relative 'schemas_3_1/classes'

require_relative 'schemas_3_1/base'
require_relative 'schemas_3_1/discriminator'
require_relative 'schemas_3_1/openapi'
require_relative 'schemas_3_1/paths'
require_relative 'schemas_3_1/path_item'
require_relative 'schemas_3_1/operation'
require_relative 'schemas_3_1/parameter'
require_relative 'schemas_3_1/reference'
require_relative 'schemas_3_1/request_body'
require_relative 'schemas_3_1/response'
require_relative 'schemas_3_1/responses'
require_relative 'schemas_3_1/components'
require_relative 'schemas_3_1/media_type'
require_relative 'schemas_3_1/schema'
require_relative 'schemas_3_1/header'
require_relative 'schemas_3_1/info'
